name: SCA
run-name: Security Scanning ⚡️

on:
  schedule:
    - cron: "34 7 * * 1-5" # Every weekday
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: {} # Top-level permissions set to none (explicit security)

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: read
      actions: read

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-images-file: ${{ github.workspace }}/docker-images.json