name: SCA
run-name: Security Scanning ⚡️

on:
  schedule:
    - cron: "0 11 * * *" # Daily at midnight UTC
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  branch_protection_rule:

permissions: {} # Top-level permissions set to none (explicit security)

jobs:
  sca:
    name: Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: read
      actions: read

    steps:
      - name: Run SCA
        uses: ministryofjustice/devsecops-actions/sca@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker-images-file: "docker-images.json"